# Generated by Django 4.1.6 on 2023-02-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
