# Generated by Django 4.1.6 on 2023-02-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shelf_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddedfooditems',
            name='brand',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='useraddedfooditems',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraddedfooditems',
            name='imageURL',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='useraddedfooditems',
            name='labels',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='useraddedfooditems',
            name='productName',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='useraddedfooditems',
            name='servingWeight',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='useraddedfooditems',
            name='weight',
            field=models.TextField(default=''),
        ),
    ]
