# Generated by Django 4.1.6 on 2023-02-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_useraddedfooditems_on_shelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddedfooditems',
            name='brand',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='useraddedfooditems',
            name='imageURL',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='useraddedfooditems',
            name='labels',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='useraddedfooditems',
            name='productName',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='useraddedfooditems',
            name='servingWeight',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='useraddedfooditems',
            name='weight',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
