# Generated by Django 4.1.4 on 2023-02-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_useraddedfooditems_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='imageURL',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
