# Generated by Django 4.1.4 on 2023-02-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_favouriterecipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
